### PR TITLE
Update integrations.mdx

### PR DESCRIPTION
**Pull request by alberttwong**
Adding in StarRocks integration to Delta Lake.

### CODE REVIEW

**Comment by alberttwong** [comment]
We are already listed at https://delta.io/integrations

**Comment by alberttwong** [comment]
LGTM

**Comment by alberttwong** [comment]
why does https://docs.delta.io/latest/integrations.html look so difference than the preview site?

**Comment by dennyglee** [comment]
Hi @alberttwong - we're working on updating the structure of the docs altogether.

**Pull request closed without merging**
