### PR TITLE
 Updated Dockerfile to the latest versions of delta-spark [v2.3.0] and deltalake [v0.8.1]

### LINKED ISSUE #44: Quickstart Issue: Exception thrown with KeyError '0'
Where the Bug was found: Location: https://github.com/delta-io/delta-docs/blob/main/static/quickstart_docker/README.md

The quickstart_docker/README.md example raises an exception when testing out the python writer.

## Exception
~~~
>>> df = pd.DataFrame(range(5))
>>> write_deltalake("/tmp/deltars_table", df)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyarrow/pandas_compat.py", line 428, in _get_columns_to_convert_given_schema
    col = df[name]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 395, in get_loc
    raise KeyError(key)
KeyError: '0'
~~~

## Fix
Adding a column name fixes the issue. 
~~~
>>> df = pd.DataFrame( {"data": range(5)} )
>>> write_deltalake("/tmp/deltars_table", df)
~~~

### PR DESCRIPTION
**Pull request by P7h**
- Also the base container has been changed to official OSS Apache Spark v3.3.2 image. 
- Pandas version has been updated to the latest compatible version supporting Delta Spark v2.3.0.
- Updated README as well to reflect these changes. 
- Tested all the steps end to end and also ran lint to fix any formatting issues.
- Also fixes #44

### CODE REVIEW

**Comment by dennyglee** [comment]
thanks @P7h - will review shortly!

**Comment by dennyglee** [comment]
@P7h could you please review the branch conflicts and resolve them first?

**Comment by dennyglee** [comment]
BTW, I did a quick test of the instructions, Python, Rust, and ROAPI and it works great.

**Comment by P7h** [comment]
> @P7h could you please review the branch conflicts and resolve them first?

Resolved the conflicts. And also tested the dockerfile and ran through all the steps in the README - all fine.

**Review by dennyglee — APPROVED** [review]
LGTM!

**Pull request merged**
