### PR TITLE
Add missed continuation

### PR DESCRIPTION
**Pull request by BlueHorn07**
When I run the code, I got error. It need continuation backslash `\`.

### CODE REVIEW

**Comment by BlueHorn07** [comment]
Hi, @dennyglee! I fixed one python backslash continuation. Please take a look at 🙏

**Comment by dennyglee** [comment]
Thanks @BlueHorn07  - this looks great!  thanks for catching this!

**Review by dennyglee — APPROVED** [review]
LGTM!

**Comment by BlueHorn07** [comment]
Thanks, @dennyglee 👍  Please, plan this PR to merge 🙏

**Comment by dennyglee** [comment]
Thanks @BlueHorn07  - there is an issue with the GitHub check, let me see what's going on here.

**Pull request merged**
